-- Mixins are just like events under the hood! This means that depending on where you're mixing into, it could be
-- beneficial to put it in a dynamic entrypoint, to enable easy modification and reloading!
-- Unfortunately here, the brewing recipe registry gets created only once on game start, so this file is not dynamic.
